---
title: "Define heart failure and stage B HF based on echo measures"
format: html
editor: visual
---

# Definition of heart failure based on echo measurements

+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Heart failure type                  | Definition                                                  | Source                                                                                                                                                                                                               | Variables      |
+=====================================+=============================================================+======================================================================================================================================================================================================================+================+
| HFrEF                               | LVEF ≤40%                                                   | Definition of HFrEF and HFpEF are base on ESC guidelines from refernce: Epidemiology of heart failure in diabetes: a disease in disguise Diabetologia (2024) 67:574–601 <https://doi.org/10.1007/s00125-023-06068-2> | lvef4dautolvq  |
+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| HFmrEF                              | LVEF 41–49%                                                 | Definition of HFrEF and HFpEF are base on ESC guidelines                                                                                                                                                             | lvef4dautolvq  |
+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| HFpEF                               | LVEF ≥50% & one of                                          | Definition of HFrEF and HFpEF are base on ESC guidelines                                                                                                                                                             | lvef4dautolvq  |
|                                     |                                                             |                                                                                                                                                                                                                      |                |
|                                     | a ) Left ventricular mass index ≥95 g/m2 (F), ≥115 g/m2 (M) |                                                                                                                                                                                                                      | lvdmassindexgm |
|                                     |                                                             |                                                                                                                                                                                                                      |                |
|                                     | b\) Left atrial volume index \>34 ml/m2                     |                                                                                                                                                                                                                      | gender         |
|                                     |                                                             |                                                                                                                                                                                                                      |                |
|                                     | c\) E/e’ ratio (rest) \>9                                   |                                                                                                                                                                                                                      |                |
+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| **Stage B heart failure**           |                                                             |                                                                                                                                                                                                                      |                |
+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Abnormal global longitudinal strain | GLS ≥ −18%                                                  |                                                                                                                                                                                                                      |                |
+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Abnormal global longitudinal strain | GLS ≥ −16%                                                  |                                                                                                                                                                                                                      |                |
+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Diastolic function                  | E/e’≥ 14 or e’\< 8 cm/s \|                                  |                                                                                                                                                                                                                      |                |
+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Left ventricular hypertrophy        | Left ventricular mass index ≥95 g/m2 (F), ≥115 g/m2 (M)     |                                                                                                                                                                                                                      |                |
+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| Left atrium enlargement             | Left atrial volume index \>34 ml/m2                         |                                                                                                                                                                                                                      |                |
+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
|                                     |                                                             |                                                                                                                                                                                                                      |                |
+-------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+

+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| Continous echo measures          | Charteristic                                                                                                                                                                                                          | Variable name |
+==================================+=======================================================================================================================================================================================================================+===============+
| e'                               | Early diastolic filling                                                                                                                                                                                               |               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| a'                               | Arterial kick                                                                                                                                                                                                         |               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| E                                | Early passive filling of left ventricle                                                                                                                                                                               |               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| A                                | Lat active filling                                                                                                                                                                                                    |               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| E/A                              | Left ventricular diastolic dysfunction                                                                                                                                                                                |               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| Global longitudinal strain (GLS) | Sutle left ventricular systolic dysfunction                                                                                                                                                                           |               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| Left ventricular mass index      | The mass of left ventricular (thickness of the muscle)                                                                                                                                                                |               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| Left ejection fraction           | A measure of systolic function                                                                                                                                                                                        |               |
|                                  |                                                                                                                                                                                                                       |               |
|                                  | If lower the heart muscle I weakened, and hence the ejection fraction is low. I cases when EF is normal but heart failure is still present, it can be charaterized by HFpEF, which is stiffening of the heart muscle. |               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| Left arterial volume             | Left ventricular diastolic dysfunction                                                                                                                                                                                |               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+

## Function for definition

```{r}
#' Echo wrangling
#'
#' @param echo_data
#'
#' @return
#' @export
#'
#' @examples
echo_data_transformation <- function(echo_data) {
  echo_data %>%
    dplyr::mutate(
      id_num = floor(record_id),
      time_point = ifelse(record_id %% 1 == 0, "baseline", "follow_up")
    ) %>%
        
    
    dplyr::mutate(
        
        
        # Left atrium enlargement
        
      LAE_lf_art_enlarg = dplyr::case_when(
        laesvialmlm >= 34 ~ "LAE",
        laesvialmlm < 34 ~ "Normal"
      ),
      LAE_lf_art_enlarg = dplyr::fct_relevel(LAE_lf_art_enlarg, "Normal"),
      
      #  Left ventricular hypertrophy
      
      LVH_lf_vent_hyptro = dplyr::case_when(
        gender == 1 & lvdmassindexgm >= 115 |
          gender == 2 & lvdmassindexgm >= 95 ~ "LVH",
        gender == 1 & lvdmassindexgm < 115 |
          gender == 2 & lvdmassindexgm < 95 ~ "Normal"
      ),
      LVH_lf_vent_hyptro = dplyr::fct_relevel(LVH_lf_vent_hyptro, "Normal"),
      
      # Diastolic dysfunction  
      
      DD_dia_dys = dplyr::case_when(
        eepsept >= 13 ~ "DD",
        eepsept < 13 ~ "Normal"
      ),
      DD_dia_dys = dplyr::fct_relevel(DD_dia_dys, "Normal"),
      
      
      #  Imparied /abnornal global longitudinal strain
      ## Remember to make all values negative in GLS
                GLS_imparied = case_when(glpsavgafi >= -16 ~ "imparied",
                                    glpsavgafi < -16 ~ "Normal"),
           GLS_imparied = fct_relevel(GLS_imparied, "Normal"),

           GLS_abnormal = case_when(glpsavgafi >= -18 ~ "abnormal",
                                    glpsavgafi < -18 ~ "Normal"),
           GLS_abnormal = fct_relevel(GLS_abnormal, "Normal"),
      
      GLS_abnormal = dplyr::fct_relevel(GLS_abnormal, "Normal"),
      
      # Ejection fraction Normal /abnormal
      
      EF_HF = dplyr::case_when(
        lvef4dautolvq <= 50 ~ "abnormal",
        lvef4dautolvq > 50 ~ "Normal"
      ),
      EF_HF = dplyr::fct_relevel(EF_HF, "Normal"),


      # HFrEF
      
      HFrEF = dplyr::case_when(
        lvef4dautolvq <= 40 ~ "HFrEF",
        lvef4dautolvq > 40 ~ "no HFrEF"
      ),
      HFrEF = dplyr::fct_relevel(HFrEF, "no HFrEF"),
      
      # HFmrEF
      
      HFmrEF = dplyr::case_when(
        lvef4dautolvq < 50 & lvef4dautolvq > 40 ~ "HFmrEF",
        lvef4dautolvq >= 50 ~ "no HFmrEF"
      ),
      HFmrEF = fct_relevel(HFrEF, "no HFmrEF"),

      # HFpEF (need work)
      HFpEF = dplyr::case_when(
        lvef4dautolvq >= 50 & (
          LVH_lf_vent_hyptro == "LVH" |
            mveeavg > 9) ~ "HFpEF",
        (LVH_lf_vent_hyptro == "normal" |
          mveeavg <= 9) &
          lvef4dautolvq >= 50 ~ "no HFpEF"
      ),
      HFpEF = dplyr::fct_relevel(HFpEF, "no HFpEF"), # Something is wrong prevalence of HFrEF are very high

      HFmrEF_rEF = dplyr::case_when(
        lvef4dautolvq < 50 ~ "HFmrEF or HFrEF",
        lvef4dautolvq >= 50 ~ "no HFmrEF or HFrEF"
      ),
      HFmrEF_rEF = dplyr::fct_relevel(HFmrEF_rEF, "no HFmrEF or HFrEF"),
      any_HF = dplyr::case_when(
        HFmrEF_rEF == "HFmrEF or HFrEF" | HFpEF == "HFpEF" ~ "Heart failure",
        HFmrEF_rEF == "no HFmrEF or HFrEF" & HFpEF == "no HFpEF" ~ "No heart failure"
      ),
      any_HF = dplyr::fct_relevel(any_HF, "No heart failure")
    )
}
```
